### PR TITLE
#163387197 setup POST/api/v1/questions endpoint

### PR DESCRIPTION
**Pull request by innocentEdosa**
#### What does this PR do?
Setup up POST/api/v1/questions endpoint

#### Description of Task to be completed?
Write test for POST/api/v1/questions endpoint
refactor createQuestion function in question controller to use postgresql database
Secure Post/question route with jwt

#### How should this be manually tested?
clone the repo 
checkout to ft-setup-create-question-endpoint-163387197 branch
run npm start
test with postman

#### Any background context you want to provide?
create question now uses persistent database

#### What are the relevant pivotal tracker stories?
#163387197

#### Screenshots

nnn

#### Questions
can this be merged?

### CODE REVIEW

**Comment by Felglitzzz** [comment]
@innocentEdosa the image u put there is ambiguous. Doesn't show the url too. Kindly fix that
@innocentEdosa your test seems to have dropped by 5.6%

**Comment by innocentEdosa** [comment]
Hello felix
i have changed the screenshots. It now contains the url.
I had some spelling error in my test script, i spelt phone number as phone numbe. I also referenced some variables wrongly like res instead of result.
i have fixed all that now  and coveralls coverage has increased but it doesn't seem to change here now.
It should show anytime soon
Thanks

**Comment by Felglitzzz** [comment]
@innocentEdosa 

- The property of your response object should be in camelcase. I see `createdby`, `createdon` doesn't follow that scheme
- You were given a response specification, is there a reason you did not follow it?

**Comment by innocentEdosa** [comment]
I apologize for the deviations
Honestly i didn't notice it. Those field names are directly from the PostgreSQL database, it converts fields names to lowercase by default. I found a resources on how to fix and i have implemented it. I added a screenshot of the fix.
Thanks

**Review by Felglitzzz — APPROVED** [review]

**Comment by Felglitzzz** [comment]
Approved @innocentEdosa

**Pull request merged**
