### PR TITLE
#163377692 Implement LFA UI feedback 

### PR DESCRIPTION
**Pull request by innocentEdosa**
#### What does this PR do?
Implement lfa ui feedback 

#### Description of Task to be completed?
Create delete meetup popup form
Design create meetup popup form
Design edit meetup popup form
Fix typo in log in form

#### How should this be manually tested?
clone the repo
checkout to bt-implement-LFA-UI-feedback-163377692
open pages in browser

#### Any background context you want to provide?
all popup form for admin page now working

#### What are the relevant pivotal tracker stories?
#163377692

#### Screenshots
screenshot_2019-01-22 questioner admin
screenshot_2019-01-22 questioner admin 1
screenshot_2019-01-22 questioner login
screenshot_2019-01-22 questioner admin 2
screenshot_2019-01-22 questioner admin 3

#### Questions
can this be merged?

### CODE REVIEW

**Comment by Felglitzzz** [comment]
@innocentEdosa kindly provide images for the fix for misspelling on sign in page and edit meet up page

**Comment by innocentEdosa** [comment]
screenshots provided
Thanks

**Comment by Felglitzzz** [comment]
@innocentEdosa check the button text for the edit form

**Comment by innocentEdosa** [comment]
sorry about that
fixed now
thanks

**Comment by Felglitzzz** [comment]
What does `bt` stands for in your branch name?

**Pull request closed without merging**
